name = "sweet_olive_harrier-7482"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "sweet_olive_harrier-7482_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "sweet_olive_harrier-7482.wasm"
command = "npm run build:release"
