name: Publish to Blockless
on:
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: write
  
jobs:
  publish-on-blockless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get epository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - run: |
          sed -i 's/template_name/${{ env.REPOSITORY_NAME }}/g' bls.toml
          cat bls.toml
      - uses: stefanzweifel/git-auto-commit-action@v4
      - name: Blockless Action Setup
        uses: txlabs/github-action-blockless-setup@v0.0.5
        with:
          BLOCKLESS_ENDPOINT_URL: https://blockless.network
      - name: Blockless Function Publish
        uses: txlabs/github-action-blockless-deploy@v0.0.3
